# DO NOT EDIT
# This file is autogenerated by build-tools/main.go

all: .boilerplate  v1alpha1/clientset/versioned/typed/cronjob/v1alpha1/cronjob.go

 v1alpha1/clientset/versioned/typed/cronjob/v1alpha1/cronjob.go:
	./code-generator/generate-groups.sh all v1alpha1 anglo-korean.github.io/crd  v1alpha1:cronjob --go-header-file $< --output-base .
