/*
Copyright Anglo Korean.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "anglo-korean.github.io/crd/cronjob/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CronjobLister helps list Cronjobs.
// All objects returned here must be treated as read-only.
type CronjobLister interface {
	// List lists all Cronjobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Cronjob, err error)
	// Cronjobs returns an object that can list and get Cronjobs.
	Cronjobs(namespace string) CronjobNamespaceLister
	CronjobListerExpansion
}

// cronjobLister implements the CronjobLister interface.
type cronjobLister struct {
	indexer cache.Indexer
}

// NewCronjobLister returns a new CronjobLister.
func NewCronjobLister(indexer cache.Indexer) CronjobLister {
	return &cronjobLister{indexer: indexer}
}

// List lists all Cronjobs in the indexer.
func (s *cronjobLister) List(selector labels.Selector) (ret []*v1alpha1.Cronjob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Cronjob))
	})
	return ret, err
}

// Cronjobs returns an object that can list and get Cronjobs.
func (s *cronjobLister) Cronjobs(namespace string) CronjobNamespaceLister {
	return cronjobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CronjobNamespaceLister helps list and get Cronjobs.
// All objects returned here must be treated as read-only.
type CronjobNamespaceLister interface {
	// List lists all Cronjobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Cronjob, err error)
	// Get retrieves the Cronjob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Cronjob, error)
	CronjobNamespaceListerExpansion
}

// cronjobNamespaceLister implements the CronjobNamespaceLister
// interface.
type cronjobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Cronjobs in the indexer for a given namespace.
func (s cronjobNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.Cronjob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Cronjob))
	})
	return ret, err
}

// Get retrieves the Cronjob from the indexer for a given namespace and name.
func (s cronjobNamespaceLister) Get(name string) (*v1alpha1.Cronjob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("cronjob"), name)
	}
	return obj.(*v1alpha1.Cronjob), nil
}
