/*
Copyright Anglo Korean.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"
	versioned "v1alpha1/clientset/versioned"
	internalinterfaces "v1alpha1/informers/externalversions/internalinterfaces"
	v1alpha1 "v1alpha1/listers/cronjob/v1alpha1"

	cronjobv1alpha1 "anglo-korean.github.io/crd/cronjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CronjobInformer provides access to a shared informer and lister for
// Cronjobs.
type CronjobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CronjobLister
}

type cronjobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCronjobInformer constructs a new informer for Cronjob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCronjobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCronjobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCronjobInformer constructs a new informer for Cronjob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCronjobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StableV1alpha1().Cronjobs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StableV1alpha1().Cronjobs(namespace).Watch(context.TODO(), options)
			},
		},
		&cronjobv1alpha1.Cronjob{},
		resyncPeriod,
		indexers,
	)
}

func (f *cronjobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCronjobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cronjobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cronjobv1alpha1.Cronjob{}, f.defaultInformer)
}

func (f *cronjobInformer) Lister() v1alpha1.CronjobLister {
	return v1alpha1.NewCronjobLister(f.Informer().GetIndexer())
}
